### PR TITLE
fix: use relative links

### PR DESCRIPTION
**Pull request by enjoyooor**
Using relative links throughout the repo

### CODE REVIEW

**Comment by wbnns** [comment]
@enjoyooor 

Thanks for submitting this, just wanted to confirm this is still in our backlog for further review. 👍

**Comment by enjoyooor** [comment]
ty @wbnns

**Review by wbnns — APPROVED** [review]
@enjoyooor 

Thanks! Tested ACK.

**Comment by wbnns** [comment]
Unrelated test is causing the CI on this PR to fail.

**Comment by wbnns** [comment]
We're going to close and leave this as-is for now; thank you for the contribution that we can keep in mind for future changes, here 🙏

**Pull request closed without merging**
